version: '3.8'

services:
  gateway_service:
    build: ./gateway_service
    ports:
      - "8000:8000"
    networks:
      - poker_net


  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
    networks:
      - poker_net
    volumes:
      - ./auth_service/data:/auth_app/auth_app/data
    environment:
      - DB_PATH=/auth_app/auth_app/data/user.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 5s
      timeout: 3s
      retries: 3


networks:
  poker_net:
    driver: bridge
    attachable: true