version: '3.8'

services:
  gateway_service:
    build: ./gateway_service
    ports:
      - "8000:8000"
    networks:
      - poker_net


  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
    networks:
      - poker_net
    volumes:
      - ./auth_service/data:/auth_app/auth_app/data
    environment:
      - DB_PATH=/auth_app/auth_app/data/user.db

  game_service:
    build: ./game_service
    ports:
      - "8004:8004"
    networks:
      - poker_net
    volumes:
      - ./game_service/data:/game_app/game_app/data
    environment:
      - DB_PATH=/game_app/game_app/data/poker.db

  user_service:
    build: ./user_service
    ports:
      - "8003:8003"
    networks:
      - poker_net
    volumes:
      - ./user_service/data:/user_app/user_app/data
    environment:
      - DB_PATH=/user_app/user_app/data/profile.db



networks:
  poker_net:
    driver: bridge
    attachable: true